version: '3.6'

services:    
  api:
    build: 
      context: .
    container_name: api
    healthcheck:
      test: curl --fail http://localhost:80/health || exit 1
      interval: 20s
      timeout: 1s
      retries: 3
      start_period: 10s
    ports:
      - "5000:80"
    networks:
      - mynetwork
    restart: always
      
  postgresdb:
    image: postgres:10
    ports:
      - "5433:5432"
    environment:
        POSTGRES_PASSWORD: Sp22!hYw
        POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:    

volumes:
  pgdata:

