# This is a basic workflow to help you get started with Actions

name: Secure-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - 
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build docker image
      uses: docker/build-push-action@v2
      with:
          # Set build context as current (root) directory
          context: .
          load: true
          tags: |
            dnaprawa/currency-viewer:latest
            dnaprawa/currency-viewer:${{ github.sha }}
    - 
      name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: dnaprawa/currency-viewer:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
    -
      name: Push docker images
      uses: docker/build-push-action@v2
      with:
          # Set build context as current (root) directory
          context: .
          push: true
          tags: |
            dnaprawa/currency-viewer:latest
            dnaprawa/currency-viewer:${{ github.sha }}

